#pragma once
#define MAP_HEIGHT 560.0
#define MAP_WIDTH 560.0
#define MAP_INTERVALS 20

#define UPDATE_PER_MS 10.0
#define PER_SECOND_IN_GAME 15.0

#define _PI_	3.14159265359
#define EPSILON 0.05

#define BATTLE_SHIP_WIDTH    MAP_WIDTH/MAP_INTERVALS*1.0
#define BATTLE_SHIP_HEIGHT    MAP_HEIGHT/MAP_INTERVALS*0.4

#define MISSILE_WIDTH	MAP_WIDTH/MAP_INTERVALS*1.0
#define MISSILE_HEIGHT	MAP_WIDTH/MAP_INTERVALS*0.5

#define LOCATION_DISPLAY_WIDTH 4

#define TEXT_PIXEL 8


#define DEF_NOVA_RANGE 3